# https://dev.azure.com/open-peer-power

trigger:
  batch: true
  branches:
    include:
      - main
pr: none
variables:
  - name: versionWheels
    value: "1.13.0-3.8-alpine3.12"
resources:
  repositories:
    - repository: azure
      type: github
      name: "open-peer-power/ci-azure"
      endpoint: "open-peer-power"

jobs:
  - template: templates/azp-job-wheels.yaml@azure
    parameters:
      builderVersion: "$(versionWheels)"
      builderApk: "build-base;libffi-dev;openssl-dev"
      builderPip: "Cython"
      skipBinary: "aiohttp"
      wheelsRequirement: "requirements.txt"
